version: '3'

services:
  blog_project_db:
    container_name: blog_project_db
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: postgres
  
  blog_project:
    environment:
      FLASK_APP: main.py
    container_name: blog_project
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file: 
      - .env
    command: python main.py
    volumes:
      - .:/BlogProject
    ports:
      - '5001:5001'
    depends_on:
      - blog_project_db
    environment:
      flask_env: 'development'
