"""empty message

Revision ID: be14caabaabb
Revises: 093fbb521c6d
Create Date: 2023-07-28 04:21:34.702132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be14caabaabb'
down_revision = '093fbb521c6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('superuser', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.drop_column('superuser')
        batch_op.drop_column('admin')

    # ### end Alembic commands ###
